app/store/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField
from wtforms.validators import Length, DataRequired, InputRequired


class StoreForm(FlaskForm):
    url = StringField('Store Url', validators=[DataRequired(), Length(0, 128)])
    key = StringField('Consumer Key', validators=[DataRequired(), Length(0, 128)])
    secret = StringField('Consumer Secret', validators=[DataRequired(), Length(0, 128)])
    version = StringField('API Version', default='wc/v3', validators=[DataRequired(), Length(0, 128)])
    active = BooleanField('Active?', default=True)
    submit = SubmitField('Submit')

app/store/__init__.py
from flask import Blueprint

store = Blueprint('store', __name__, template_folder='templates', static_folder='static')

from .views import *

app/store/views.py
from flask import render_template, redirect, url_for, abort, flash, request,\
    current_app, make_response
from .. import db
from ..models import Store
from . import store as app
from .forms import StoreForm


@app.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Store.query.order_by(Store.id.desc()).paginate(
        page, per_page=current_app.config['STORES_PER_PAGE'],
        error_out=False
    )
    stores = pagination.items

    return render_template('index.html', stores=stores, pagination=pagination)


@app.route('/create', methods=['GET', 'POST'])
def create():
    form = StoreForm()

    if form.validate_on_submit():
        store = Store(
            url=form.url.data,
            key=form.key.data,
            secret=form.secret.data,
            version=form.version.data,
            active=form.active.data
        )

        try:
            db.session.add(store)
            db.session.commit()

            flash("Your store has been updated.")
        except Exception as e:
            flash("Error: Your store hasn't been updated.")

        return redirect(url_for('store.index'))

    return render_template('modify.html', form=form)


@app.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    store = Store.query.get_or_404(id)
    form = StoreForm()

    if form.validate_on_submit():
        store.id = id
        store.url = form.url.data
        store.key = form.key.data
        store.secret = form.secret.data
        store.version = form.version.data
        store.active = form.active.data

        try:
            db.session.commit()

            flash("Your store has been updated.")
        except Exception as e:
            flash("Error: Your store hasn't been updated.")

        return redirect(url_for('store.index'))

    form.url.data = store.url
    form.key.data = store.key
    form.secret.data = store.secret
    form.version.data = store.version
    form.active.data = store.active
    return render_template('modify.html', form=form)


@app.route('/active_store/<int:id>', methods=['GET'])
def active_store(id):
    store = Store.query.get_or_404(id)
    store.active_store()

    try:
        db.session.commit()

        flash("Your store has been updated.")
    except Exception as e:
        flash("Error: Your store hasn't been updated.")

    return redirect(url_for('store.index'))


@app.route('/deactive_store/<int:id>', methods=['GET'])
def deactive_store(id):
    store = Store.query.get_or_404(id)
    store.deactive_store()

    try:
        db.session.commit()

        flash("Your store has been updated.")
    except Exception as e:
        flash("Error: Your store hasn't been updated.")
        raise e

    return redirect(url_for('store.index'))

app/store/templates/index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block page_content %}
    <div class="text-right">
        <a class="btn btn-primary" href="{{ url_for('store.create') }}">Add Store</a>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Stores</div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Store URL</th>
                    <th>API Version</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
            {% for store in stores %}
                <tr class="{% if store.active %}success{% else %}danger{% endif %}">
                    <td>{{ store.id }}</td>
                    <td>{{ store.url }}</td>
                    <td>{{ store.version }}</td>
                    <td>{% if store.active %}Active{% else %}Deactive{% endif %}</td>
                    <td>
                        {% if store.active %}
                        <a class="btn-sm btn-danger" href="{{ url_for('store.deactive_store', id=store.id) }}">Deactive</a>
                        {% else %}
                        <a class="btn-sm btn-success" href="{{ url_for('store.active_store', id=store.id) }}">Active</a>
                        {% endif %}
                        <a class="btn-sm btn-primary" href="{{ url_for('store.update', id=store.id) }}">Edit</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if pagination %}
        {{ macros.pagination_widget(pagination, '.index') }}
    {% endif %}
{% endblock %}

app/store/templates/modify.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="panel panel-default">
        <div class="panel-heading">Store Infomation</div>
        <div class="panel-body">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}